apiVersion: v1
kind: Service
metadata:
  name: nyx-python-backend-api-service
  namespace: nyx-backend-ns
  labels:
    app: nyx-backend-python
spec:
  type: LoadBalancer
  selector:
    app: nyx-backend-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  sessionAffinity: ClientIP
